# https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
sudo: false
dist: xenial

language: go
go:
  - "1.13"

env:
  - GO111MODULE=on

# Only clone the most recent commit.
git:
  depth: 1

before_install:
  # Dump environment variables
  - printenv

install:
  - "go get -u -v github.com/kevinburke/go-bindata/..."

before_script:
  - "make magneticod"
  - "make magneticow"
  - "make image"

script:
  # The Unit Tests
  - "make test"

  # Static Analysis (vet)
  - "make vet"

  # Check formatting
  - "make check-formatting"
