# python 3.5 is the latest version that works with the stable version of pyinstaller
FROM python:3.5

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY . .
# need to latest version to work around the 'yield inside async function' error (jinja2)
RUN pip install jinja2==2.8.1
RUN pip install pyinstaller
RUN pip install -e .
RUN pyinstaller magneticow.spec
CMD ["base64", "-w 0", "dist/magneticow"]
